os:
- linux
- osx

sudo: required

language: cpp
compiler:
  - gcc
  - clang

osx_image: xcode7

matrix:
  exclude:
    - os: osx
      compiler: gcc

before_install:
  - ./.travis-deps.sh

script:
  - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then cmake . ; fi
  - if [ "${TRAVIS_OS_NAME}" = "osx" ]; then cmake . -DLLVM_DIR=/usr/local/Cellar/llvm/3.6.2/share/llvm/cmake ; fi
  - make -j 2
  - make test
