os:
- linux
- osx

language: cpp
compiler:
  - gcc
  - clang

matrix:
  exclude:
   - os: osx
    compiler: gcc

before_install:
  - ./.travis-deps.sh

script:
  - cmake .
  - make -j 2
  - make test
